name: zookeeper
base: core18
version: '3.4.13'
summary: Apache ZooKeeper enables highly reliable distributed coordination.
description: ZooKeeper is a centralized service for maintaining configuration information, naming, providing distributed synchronization, and providing group services.
grade: stable
confinement: strict

apps:
  zookeeper:
    command: zookeeper-wrapper.sh start-foreground
    stop-command: zookeeper-wrapper.sh stop
    daemon: simple
    plugs: [network, network-bind, removable-media]
  client:
    command: zkCli-wrapper.sh 
    plugs: [network]

parts:
  zookeeper:
    plugin: ant
    source: https://github.com/apache/zookeeper.git
    source-depth: 1
    source-tag: release-3.4.13
    override-build: |-
      snapcraftctl build

      cp ./build/zookeeper-3.4.13.jar .
      cp ./conf/zoo_sample.cfg ./conf/zoo.cfg
      (cd ../; tar -czf zookeeper.tgz ./build)
  wrapper:
    plugin: dump
    source: snap/local
  install:
    plugin: nil
    after:
      - zookeeper
    build-packages:
      - openjdk-8-jre
    override-build: |-
      tarball=/root/parts/zookeeper/zookeeper.tgz

      mkdir -p $SNAPCRAFT_PART_INSTALL/opt/zookeeper
      (cd $SNAPCRAFT_PART_INSTALL/opt; tar --strip-components=2 -C zookeeper -xzvf $tarball)
    stage:
      - opt
    prime:
      - opt
